### ISSUE TITLE
Badges not being copied to location defined in --save

### ISSUE THREAD

**Issue by corydorning** [adam-sokolowski/badges#1]
Have the following script defined in `package.json`:
```
"scripts": {
    "test": "jest --coverage && coverage-badges --read=./coverage/coverage-final.json --save=./coverage/badges"
  },
```

Only the `average.svg` badge is being copied to `./coverage/badges`.

**Comment by corydorning** [comment]
Just viewed the `average.svg` and it showing `NaN%` so i'm likely doing something wrong. Just not sure what.

**Comment by corydorning** [comment]
problem solved. just needed to add `json-summary` to the jest `coverageReporters`. thanks for the module!

**Comment by adam-sokolowski** [comment]
thank you! I'll add a clearer description to readme and better error handling
